version: "3.7"

services:

  postgres:
    image: postgres:12
    init: true
    env_file:
      - ./env/.postgres.env

  redis:
    image: redis:5
    init: true

  app:
    image: usedgoodreads/app
    init: true
    command: bash -c "wait-for-it -s -t 60 postgres:5432 && wait-for-it -s -t 60 redis:6379 -- gunicorn 'usedgoodreads.__main__:main()'"
    env_file:
      - ./env/.app.env
    depends_on:
      - postgres
      - redis
      - worker

  firefox:
    image: selenium/standalone-firefox:3.141.59-20200515
    init: true
    ipc: host

  nginx:
    image: nginx:1.18.0
    env_file:
      - env/.nginx.env
    command: /bin/bash -c "envsubst '$$NGINX_PORT $$NGINX_SSL_PORT $$NGINX_HOST' < /etc/nginx/conf.d/conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/conf.template
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    # #TODO Without this dependency the configuration of nginx can not use `app`
    # as a hostname. Why?

  worker:
    image: usedgoodreads/app
    init: true
    command: bash -c "wait-for-it -s -t 60 postgres:5432 && wait-for-it -s -t 60 redis:6379 -- rq worker --url redis://redis:6379"
    env_file:
      - ./env/.app.env
    depends_on:
      - postgres
      - redis
      - firefox
