version: "3.7"
services:
  postgres:
    image: postgres:12
    init: true
    ports:
      - "5432:5432"
    env_file:
      - ./env/.postgres.env
  redis:
    image: redis:5
    init: true
    ports:
      - "6379:6379"
    env_file:
      - ./env/.redis.env
  backend:
    image: usedgoodreads/backend
    build: backend
    init: true
    command: bash -c "wait-for-it -s -t 60 -h postgres -p 5432 && wait-for-it -s -t 60 -h redis -p 6379 -- sleep 10"
    ports:
      - "5000:5000"
    env_file:
      - ./env/.backend.env
    volumes:
      - ./backend:/home/python/app
    depends_on:
      - postgres
      - redis
  worker:
    image: usedgoodreads/backend
    build: backend
    init: true
    command: bash -c "wait-for-it -s -t 60 -h redis -p 6379 -- rq worker --url redis://redis:6379"
    env_file:
      - ./env/.backend.env
    volumes:
      - ./backend:/home/python/app
    depends_on:
      - postgres
      - redis
  frontend:
    image: usedgoodreads/frontend
    build: frontend
    init: true
    command: bash -c "wait-for-it -s -t 60 -h backend -p 5000 -- sleep 10"
    ports:
      - "3000:3000"
    env_file:
      - ./env/.frontend.env
    volumes:
      - ./frontend:/home/node/app
    depends_on:
      - backend
