version: "3.7"

services:

  app:
    build: ./app
    volumes:
      - ./app:/home/python/app

  worker:
    build: ./app
    volumes:
      - ./app:/home/python/app

  nginx:
    volumes:
      - ./nginx/certs:/certs
    ports:
      - "80:80"
      - "443:443"
